version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3    
    depends_on:
      db:
        condition: service_healthy

    networks:
      - daniele-net
      
  db:
    image: postgres
    networks:
      - daniele-net
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=daniele_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  react-ui:
    build:
      context: ../nfe-front-service
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./nfe-front-service:/usr/src/app/nfe-front-service
       - /usr/src/app/nfe-front-service/node_modules
  nf-upload:
    build: 
      context: ../nfe-upload-service
    ports:
      - 8083:8083
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRES_ADDRESS=db
      - POSTGRES_PORT=5432
      - RABBBIT_ADDRESS=rabbitmq
      - PATH_ROOT=data-file/      
      
    volumes:
       - file-shared:/data-file/input

    networks:
      - daniele-net

  nf-process:
    build: 
      context: ../nfe-process-service
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBBIT_ADDRESS=rabbitmq
      - RABBBIT_PORT=5672
      - PATH_ROOT=data-file/
      
    volumes:
       - file-shared:/data-file/input


    networks:
      - daniele-net
volumes:
    rabbitmq_data:
    rabbitmq_log:
    file-shared:      
      name: file-shared-volume-new
    
networks:
  daniele-net:
    driver: bridge
