version: '3'
services:
  react-ui:
    build:
      context: ../nfe-front-service
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./nfe-front-service:/usr/src/app/nfe-front-service
       - /usr/src/app/nfe-front-service/node_modules